-- MySQL Script generated by MySQL Workbench
-- Sat Nov  4 17:51:20 2017
-- model: New model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema card_market
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema card_market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `card_market` DEFAULT CHARACTER SET utf8 ;
USE `card_market` ;

-- -----------------------------------------------------
-- Table `card_market`.`Type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Type` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Type` (
  `typeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`typeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`SubType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`SubType` ;

CREATE TABLE IF NOT EXISTS `card_market`.`SubType` (
  `subTypeID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`subTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Rarity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Rarity` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Rarity` (
  `rarityID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL,
  `abbr` VARCHAR(3) NULL,
  PRIMARY KEY (`rarityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Language` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Language` (
  `languageID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `abbr` VARCHAR(3) NULL,
  PRIMARY KEY (`languageID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Set`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Set` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Set` (
  `setID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `abbr` VARCHAR(5) NULL,
  PRIMARY KEY (`setID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Condition` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Condition` (
  `conditionId` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NULL,
  `abbr` VARCHAR(5) NULL,
  PRIMARY KEY (`conditionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Card` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Card` (
  `cardID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL,
  `firstEd` TINYINT(1) NULL,
  `description` VARCHAR(1000) NULL,
  `imageUrl` VARCHAR(45) NULL,
  `typeID` INT NOT NULL,
  `subTypeID` INT NOT NULL,
  `rarityID` INT NOT NULL,
  `languageID` INT NOT NULL,
  `setID` INT NOT NULL,
  `conditionId` INT NOT NULL,
  PRIMARY KEY (`cardID`),
  INDEX `fk_Card_Type1_idx` (`typeID` ASC),
  INDEX `fk_Card_SubType1_idx` (`subTypeID` ASC),
  INDEX `fk_Card_Rarity1_idx` (`rarityID` ASC),
  INDEX `fk_Card_Language1_idx` (`languageID` ASC),
  INDEX `fk_Card_Set1_idx` (`setID` ASC),
  INDEX `fk_Card_Condition1_idx` (`conditionId` ASC),
  CONSTRAINT `fk_Card_Type1`
    FOREIGN KEY (`typeID`)
    REFERENCES `card_market`.`Type` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_SubType1`
    FOREIGN KEY (`subTypeID`)
    REFERENCES `card_market`.`SubType` (`subTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Rarity1`
    FOREIGN KEY (`rarityID`)
    REFERENCES `card_market`.`Rarity` (`rarityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Language1`
    FOREIGN KEY (`languageID`)
    REFERENCES `card_market`.`Language` (`languageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Set1`
    FOREIGN KEY (`setID`)
    REFERENCES `card_market`.`Set` (`setID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Condition1`
    FOREIGN KEY (`conditionId`)
    REFERENCES `card_market`.`Condition` (`conditionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Country` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Country` (
  `countryID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `abbr` VARCHAR(3) NULL,
  PRIMARY KEY (`countryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`ShippingAddressTemplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`ShippingAddressTemplate` ;

CREATE TABLE IF NOT EXISTS `card_market`.`ShippingAddressTemplate` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(200) NULL,
  `zipcode` VARCHAR(6) NULL,
  `city` VARCHAR(100) NULL,
  `countryID` INT NOT NULL,
  PRIMARY KEY (`addressID`),
  INDEX `fk_Address_Country1_idx` (`countryID` ASC),
  CONSTRAINT `fk_Address_Country10`
    FOREIGN KEY (`countryID`)
    REFERENCES `card_market`.`Country` (`countryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Credibility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Credibility` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Credibility` (
  `credibilityID` INT NOT NULL,
  `name` VARCHAR(80) NULL,
  `description` VARCHAR(150) NULL,
  PRIMARY KEY (`credibilityID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`User` ;

CREATE TABLE IF NOT EXISTS `card_market`.`User` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `cardsBought` INT NULL,
  `cardsSold` INT NULL,
  `addressID` INT NOT NULL,
  `credibilityID` INT NOT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_User_ShippingAddressTemplate1_idx` (`addressID` ASC),
  INDEX `fk_User_Credibility1_idx` (`credibilityID` ASC),
  CONSTRAINT `fk_User_ShippingAddressTemplate1`
    FOREIGN KEY (`addressID`)
    REFERENCES `card_market`.`ShippingAddressTemplate` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Credibility1`
    FOREIGN KEY (`credibilityID`)
    REFERENCES `card_market`.`Credibility` (`credibilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Cart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Cart` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Cart` (
  `cartID` INT NOT NULL AUTO_INCREMENT,
  `User_userID` INT NOT NULL,
  PRIMARY KEY (`cartID`),
  INDEX `fk_Cart_User1_idx` (`User_userID` ASC),
  CONSTRAINT `fk_Cart_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `card_market`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`ShippingAddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`ShippingAddress` ;

CREATE TABLE IF NOT EXISTS `card_market`.`ShippingAddress` (
  `addressID` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(200) NULL,
  `zipcode` VARCHAR(6) NULL,
  `city` VARCHAR(100) NULL,
  `countryID` INT NOT NULL,
  PRIMARY KEY (`addressID`),
  INDEX `fk_Address_Country1_idx` (`countryID` ASC),
  CONSTRAINT `fk_Address_Country1`
    FOREIGN KEY (`countryID`)
    REFERENCES `card_market`.`Country` (`countryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`PaymentMethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`PaymentMethod` ;

CREATE TABLE IF NOT EXISTS `card_market`.`PaymentMethod` (
  `paymentMethodID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL,
  `description` VARCHAR(100) NULL,
  PRIMARY KEY (`paymentMethodID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`Order` ;

CREATE TABLE IF NOT EXISTS `card_market`.`Order` (
  `orderID` INT NOT NULL AUTO_INCREMENT,
  `details` VARCHAR(45) NULL,
  `userID` INT NOT NULL,
  `addressID` INT NOT NULL,
  `paymentMethodID` INT NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_Order_User1_idx` (`userID` ASC),
  INDEX `fk_Order_Address1_idx` (`addressID` ASC),
  INDEX `fk_Order_PaymentMethod1_idx` (`paymentMethodID` ASC),
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `card_market`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_Address1`
    FOREIGN KEY (`addressID`)
    REFERENCES `card_market`.`ShippingAddress` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_PaymentMethod1`
    FOREIGN KEY (`paymentMethodID`)
    REFERENCES `card_market`.`PaymentMethod` (`paymentMethodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`CardOffer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`CardOffer` ;

CREATE TABLE IF NOT EXISTS `card_market`.`CardOffer` (
  `Card_cardID` INT NOT NULL,
  `User_userID` INT NOT NULL,
  `quantity` INT NULL DEFAULT 1,
  `price` DECIMAL NULL DEFAULT 1,
  `reserved` TINYINT(1) NULL DEFAULT 0,
  `cartID` INT NULL,
  PRIMARY KEY (`Card_cardID`, `User_userID`),
  INDEX `fk_Card_has_User_User1_idx` (`User_userID` ASC),
  INDEX `fk_Card_has_User_Card1_idx` (`Card_cardID` ASC),
  INDEX `fk_Card_has_User_Cart1_idx` (`cartID` ASC),
  CONSTRAINT `fk_Card_has_User_Card1`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `card_market`.`Card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_has_User_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `card_market`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_has_User_Cart1`
    FOREIGN KEY (`cartID`)
    REFERENCES `card_market`.`Cart` (`cartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `card_market`.`SoldCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`SoldCard` ;

CREATE TABLE IF NOT EXISTS `card_market`.`SoldCard` (
  `soldCardID` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NULL DEFAULT 1,
  `price` DECIMAL NULL DEFAULT 1,
  `reserved` TINYINT(1) NULL DEFAULT 0,
  `Card_cardID` INT NOT NULL,
  `buyerID` INT NOT NULL,
  `sellerID` INT NOT NULL,
  `orderID` INT NOT NULL,
  PRIMARY KEY (`soldCardID`),
  INDEX `fk_Card_has_User_Card1_idx` (`Card_cardID` ASC),
  INDEX `fk_SoldCard_User1_idx` (`buyerID` ASC),
  INDEX `fk_SoldCard_User2_idx` (`sellerID` ASC),
  INDEX `fk_SoldCard_Order1_idx` (`orderID` ASC),
  CONSTRAINT `fk_Card_has_User_Card10`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `card_market`.`Card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SoldCard_User1`
    FOREIGN KEY (`buyerID`)
    REFERENCES `card_market`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SoldCard_User2`
    FOREIGN KEY (`sellerID`)
    REFERENCES `card_market`.`User` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SoldCard_Order1`
    FOREIGN KEY (`orderID`)
    REFERENCES `card_market`.`Order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
