-- MySQL Script generated by MySQL Workbench
-- 11/24/17 23:15:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema card_market
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `card_market` ;

-- -----------------------------------------------------
-- Schema card_market
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `card_market` DEFAULT CHARACTER SET utf8 ;
USE `card_market` ;

-- -----------------------------------------------------
-- Table `card_market`.`cardcondition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`cardcondition` ;

CREATE TABLE IF NOT EXISTS `card_market`.`cardcondition` (
  `conditionId` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(70) NULL DEFAULT NULL,
  `abbr` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`conditionId`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`language` ;

CREATE TABLE IF NOT EXISTS `card_market`.`language` (
  `languageID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  `abbr` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`languageID`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`rarity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`rarity` ;

CREATE TABLE IF NOT EXISTS `card_market`.`rarity` (
  `rarityID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NULL DEFAULT NULL,
  `abbr` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`rarityID`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`cardset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`cardset` ;

CREATE TABLE IF NOT EXISTS `card_market`.`cardset` (
  `setID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `abbr` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`setID`))
ENGINE = InnoDB
AUTO_INCREMENT = 74
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`subtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`subtype` ;

CREATE TABLE IF NOT EXISTS `card_market`.`subtype` (
  `subTypeID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`subTypeID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`type` ;

CREATE TABLE IF NOT EXISTS `card_market`.`type` (
  `typeID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`typeID`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`card`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`card` ;

CREATE TABLE IF NOT EXISTS `card_market`.`card` (
  `cardID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NULL DEFAULT NULL,
  `firstEd` TINYINT(1) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `imageUrl` VARCHAR(45) NULL DEFAULT NULL,
  `typeID` INT(11) NOT NULL,
  `subTypeID` INT(11) NOT NULL,
  `rarityID` INT(11) NOT NULL,
  `languageID` INT(11) NOT NULL,
  `setID` INT(11) NOT NULL,
  `conditionId` INT(11) NOT NULL,
  PRIMARY KEY (`cardID`),
  INDEX `fk_Card_Type1_idx` (`typeID` ASC),
  INDEX `fk_Card_SubType1_idx` (`subTypeID` ASC),
  INDEX `fk_Card_Rarity1_idx` (`rarityID` ASC),
  INDEX `fk_Card_Language1_idx` (`languageID` ASC),
  INDEX `fk_Card_Set1_idx` (`setID` ASC),
  INDEX `fk_Card_Condition1_idx` (`conditionId` ASC),
  CONSTRAINT `fk_Card_Condition1`
    FOREIGN KEY (`conditionId`)
    REFERENCES `card_market`.`cardcondition` (`conditionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Language1`
    FOREIGN KEY (`languageID`)
    REFERENCES `card_market`.`language` (`languageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Rarity1`
    FOREIGN KEY (`rarityID`)
    REFERENCES `card_market`.`rarity` (`rarityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Set1`
    FOREIGN KEY (`setID`)
    REFERENCES `card_market`.`cardset` (`setID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_SubType1`
    FOREIGN KEY (`subTypeID`)
    REFERENCES `card_market`.`subtype` (`subTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_Type1`
    FOREIGN KEY (`typeID`)
    REFERENCES `card_market`.`type` (`typeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 754
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`credibility`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`credibility` ;

CREATE TABLE IF NOT EXISTS `card_market`.`credibility` (
  `credibilityID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  `description` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`credibilityID`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`country` ;

CREATE TABLE IF NOT EXISTS `card_market`.`country` (
  `countryID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `abbr` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`countryID`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`shippingaddresstemplate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`shippingaddresstemplate` ;

CREATE TABLE IF NOT EXISTS `card_market`.`shippingaddresstemplate` (
  `addressID` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `zipcode` VARCHAR(6) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `countryID` INT(11) NOT NULL,
  PRIMARY KEY (`addressID`),
  INDEX `fk_Address_Country1_idx` (`countryID` ASC),
  CONSTRAINT `fk_Address_Country10`
    FOREIGN KEY (`countryID`)
    REFERENCES `card_market`.`country` (`countryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`user` ;

CREATE TABLE IF NOT EXISTS `card_market`.`user` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NULL DEFAULT NULL,
  `password` VARCHAR(100) NULL DEFAULT NULL,
  `cardsBought` INT(11) NULL DEFAULT NULL,
  `cardsSold` INT(11) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `addressID` INT(11) NULL DEFAULT NULL,
  `credibilityID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`userID`),
  INDEX `fk_User_ShippingAddressTemplate1_idx` (`addressID` ASC),
  INDEX `fk_User_Credibility1_idx` (`credibilityID` ASC),
  CONSTRAINT `fk_User_Credibility1`
    FOREIGN KEY (`credibilityID`)
    REFERENCES `card_market`.`credibility` (`credibilityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_ShippingAddressTemplate1`
    FOREIGN KEY (`addressID`)
    REFERENCES `card_market`.`shippingaddresstemplate` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`cardoffer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`cardoffer` ;

CREATE TABLE IF NOT EXISTS `card_market`.`cardoffer` (
  `cardOfferID` INT(11) NOT NULL AUTO_INCREMENT,
  `Card_cardID` INT(11) NOT NULL,
  `User_userID` INT(11) NOT NULL,
  `quantity` INT(11) NULL DEFAULT '1',
  `price` DECIMAL(10,0) NULL DEFAULT '1',
  `reserved` TINYINT(1) NULL DEFAULT '0',
  `reservedCardID` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`cardOfferID`),
  INDEX `fk_Card_has_User_User1_idx` (`User_userID` ASC),
  INDEX `fk_Card_has_User_Card1_idx` (`Card_cardID` ASC),
  CONSTRAINT `fk_Card_has_User_Card1`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `card_market`.`card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Card_has_User_User1`
    FOREIGN KEY (`User_userID`)
    REFERENCES `card_market`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`reservedCard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`reservedCard` ;

CREATE TABLE IF NOT EXISTS `card_market`.`reservedCard` (
  `reservedCardID` INT NOT NULL,
  `cardoffer_cardOfferID` INT(11) NOT NULL,
  `user_userID` INT(11) NOT NULL,
  `quantity` INT(11) NULL,
  PRIMARY KEY (`reservedCardID`),
  INDEX `fk_reservedCard_cardoffer1_idx` (`cardoffer_cardOfferID` ASC),
  INDEX `fk_reservedCard_user1_idx` (`user_userID` ASC),
  CONSTRAINT `fk_reservedCard_cardoffer1`
    FOREIGN KEY (`cardoffer_cardOfferID`)
    REFERENCES `card_market`.`cardoffer` (`cardOfferID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservedCard_user1`
    FOREIGN KEY (`user_userID`)
    REFERENCES `card_market`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`shippingaddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`shippingaddress` ;

CREATE TABLE IF NOT EXISTS `card_market`.`shippingaddress` (
  `addressID` INT(11) NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(200) NULL DEFAULT NULL,
  `zipcode` VARCHAR(6) NULL DEFAULT NULL,
  `city` VARCHAR(100) NULL DEFAULT NULL,
  `countryID` INT(11) NOT NULL,
  PRIMARY KEY (`addressID`),
  INDEX `fk_Address_Country1_idx` (`countryID` ASC),
  CONSTRAINT `fk_Address_Country1`
    FOREIGN KEY (`countryID`)
    REFERENCES `card_market`.`country` (`countryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`paymentmethod`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`paymentmethod` ;

CREATE TABLE IF NOT EXISTS `card_market`.`paymentmethod` (
  `paymentMethodID` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NULL DEFAULT NULL,
  `description` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`paymentMethodID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`order` ;

CREATE TABLE IF NOT EXISTS `card_market`.`order` (
  `orderID` INT(11) NOT NULL AUTO_INCREMENT,
  `details` VARCHAR(45) NULL DEFAULT NULL,
  `userID` INT(11) NOT NULL,
  `addressID` INT(11) NOT NULL,
  `paymentMethodID` INT(11) NOT NULL,
  PRIMARY KEY (`orderID`),
  INDEX `fk_Order_User1_idx` (`userID` ASC),
  INDEX `fk_Order_Address1_idx` (`addressID` ASC),
  INDEX `fk_Order_PaymentMethod1_idx` (`paymentMethodID` ASC),
  CONSTRAINT `fk_Order_Address1`
    FOREIGN KEY (`addressID`)
    REFERENCES `card_market`.`shippingaddress` (`addressID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_PaymentMethod1`
    FOREIGN KEY (`paymentMethodID`)
    REFERENCES `card_market`.`paymentmethod` (`paymentMethodID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`userID`)
    REFERENCES `card_market`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `card_market`.`soldcard`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `card_market`.`soldcard` ;

CREATE TABLE IF NOT EXISTS `card_market`.`soldcard` (
  `soldCardID` INT(11) NOT NULL AUTO_INCREMENT,
  `quantity` INT(11) NULL DEFAULT '1',
  `price` DECIMAL(10,0) NULL DEFAULT '1',
  `Card_cardID` INT(11) NOT NULL,
  `buyerID` INT(11) NOT NULL,
  `sellerID` INT(11) NOT NULL,
  `orderID` INT(11) NOT NULL,
  PRIMARY KEY (`soldCardID`),
  INDEX `fk_Card_has_User_Card1_idx` (`Card_cardID` ASC),
  INDEX `fk_SoldCard_User1_idx` (`buyerID` ASC),
  INDEX `fk_SoldCard_User2_idx` (`sellerID` ASC),
  INDEX `fk_SoldCard_Order1_idx` (`orderID` ASC),
  CONSTRAINT `fk_Card_has_User_Card10`
    FOREIGN KEY (`Card_cardID`)
    REFERENCES `card_market`.`card` (`cardID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SoldCard_Order1`
    FOREIGN KEY (`orderID`)
    REFERENCES `card_market`.`order` (`orderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SoldCard_User1`
    FOREIGN KEY (`buyerID`)
    REFERENCES `card_market`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SoldCard_User2`
    FOREIGN KEY (`sellerID`)
    REFERENCES `card_market`.`user` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
